baseURL = "https://isabeldahlgren.github.io"
title = "Isabel Dahlgren"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Isabel Dahlgren"
  copyright = "Copyright Â© 2024 Isabel Dahlgren"
  dark = "on"
  highlight = true

[menu]

  [[menu.main]]
    identifier = "notes"
    name = "notes"
    title = "notes"
    url = "/notes/"
    weight = 10

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
