baseURL = "https://isabeldahlgren.github.io"
title = "Isabel Dahlgren"
theme = "lines"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[pagination]
  pagerSize = 999

[params]
  description = "Isabel Dahlgren"
  copyright = "Copyright Â© 2025 Isabel Dahlgren"
  dark = "on"
  highlight = true

[menu]

  [[menu.main]]
    identifier = "index"
    name       = "Posts"
    url        = "/"
    weight     = -111

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "photos"
    name = "Photos"
    url = "/photos/"
    weight = 15

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS"]

